Review my branch
NeNorvalls/Night-Owl-Streamers pull request #1
Opened 2022-08-26 14:53 UTC by NeNorvalls

PLease check it out!

2022-09-01 20:06 UTC, NeNorvalls commented
Project ready for reviewing..

2022-09-02 08:42 UTC, Fermain requested changes
There are no major issues but the way you are working with Bootstrap + SCSS needs improvement. You haven't customised bootstrap, just extended it with your own styles.

2022-09-02 08:42 UTC, Fermain commented on src/scss/_partials/_global.scss
> +*,
This block is aggressive, you shouldn't be applying this many styles to every single element. It will cause trouble with bootstrap components.

2022-09-02 08:42 UTC, Fermain commented on src/scss/_partials/_global.scss
> +    color: $textColor;
Why not set the color with a CSS class? `.text-primary` for example then you can set the primary colour.

2022-09-02 08:42 UTC, Fermain commented on src/scss/_partials/_global.scss
> +    color: $textColor;
You should be overriding the default text color in BS instead

2022-09-02 14:22 UTC, RobertDacian commented
Hehe, looking good :)

2022-09-18 17:52 UTC, merged